# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build Image Tag
      run: git_hash=$(git rev-parse --short "$GITHUB_SHA")

    - name: Build Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: zzahid99/gitops-argocd
        tags: ${GITHUB_REF##*/}-$git_hash
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
