# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Print SHA
      run: echo "${GITHUB_SHA::7}"

    - name: Build Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: zzahid99/gitops-argocd
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Update Version
      run: |
          version=$(cat ./charts/helm-example/values.yaml | grep version: | awk '{print $2}')
          git_sha=${GITHUB_SHA::7}
          sed -i "s/$version/main-$git_sha/" ./charts/helm-example/values.yaml
    
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Version updated
